### ISSUE TITLE
Cool just what i was looking for!

### ISSUE THREAD

**Issue by rijotech** [faahmed/ppm-view#1]
This is not an issues is just a question, how can i directly display the ppm image into the camba without the upload funtion?

**Comment by faahmed** [comment]
@rijotech 

Inside the canvas element I would try adding an `<img>` tag. Example:

```
<canvas>
<img src="images/yourimage.ppm" width="150" height="150" alt=""/>
</canvas>
```

Let me know if this works

**Comment by rijotech** [comment]
> @rijotech
> 
> Inside the canvas element I would try adding an `<img>` tag. Example:
> 
> ```
> <canvas>
> <img src="images/yourimage.ppm" width="150" height="150" alt=""/>
> </canvas>
> ```
> 
> Let me know if this works

Nope that didn't work.
If i select the file and click upload it works!

**Comment by faahmed** [comment]
@rijotech 

Based on my research, canvas doesn't support ppm. So this upload function or similar functions are the only way to do it.

**Comment by rijotech** [comment]
That's weird since the image is being loaded into the canvas.
There is a way to trigger upload a spesific image to fool javascript into loading the ppm image?

**Comment by faahmed** [comment]
It's working since we're reading the bytes manually and putting image data to the canvas. That's the part which seems to be built-in for other image formats but not for .ppm.

We can probably try renaming the .ppm file as .bmp, and then using the above method of adding an <img... tag. 

Also, if the above img tag thing does not work for a legitimate bmp file, then we did something wrong
